sudo: required

services:
    - docker

before_install:
    - docker build -t naidudsp/loginapp .

script:
    - docker run naidudsp/loginapp npm test

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push naidudsp/loginapp

deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: docker-loginapp
    env: DockerLoginapp-env
    bucket_name: elasticbeanstalk-ap-south-1-112902673347
    bucket_path: docker-loginapp
    on:
        branch: master
    access_key_id: AKIARUSMGCPB7ELPPQON
    secret_acces_key: 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
